### ISSUE TITLE
Error on burstsearch when the leakage value is not specified

### ISSUE THREAD

**Issue by chungjjang80** [tritemio/FRETBursts#32]
Without the specification on Lk, Burstsearch is not working and I have got the message below...
(It was running on Python 3.5 version.)

```
C:\Users\SangYoon\Anaconda3\lib\site-packages\fretbursts\burstlib.py in get_leakage_array(self)
   2275         leakage = self.leakage
   2276         Lk = np.r_[[leakage]*self.nch] if np.size(leakage) == 1 else leakage
-> 2277         Lk *= self.chi_ch
   2278         return Lk
   2279 

TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int32') with casting rule 'same_kind'
```

**Comment by tritemio** [comment]
Thanks for the bug report. This bug is due to a change in numpy 1.10 which has a different default casting rules than previous versions. From numpy [release notes](http://docs.scipy.org/doc/numpy-1.10.1/release.html):

> Default casting for inplace operations will change to ‘same_kind’ in Numpy 1.10.0. This will certainly break some code that is currently ignoring the warning.

While `Data.__init__` uses a float (i.e 0.0) as default value for leakage when not specified, several loader functions in `loader.py` explicitly pass an integer value (i.e. 0). 

The fix is simple and involves making sure that `Data.leakage` is always a float. I think the best place to fix this is replacing `leakage` with `float(leakage)` in `Data.__init__`, line 703:

https://github.com/tritemio/FRETBursts/blob/master/fretbursts/burstlib.py#L703

@chungjjang80, can you submit a Pull Request with the fix?

**Comment by tritemio** [comment]
As a workaround, adding:

```
d.leakage = 0.
```

before running the burst search avoids the error.
