### ISSUE TITLE
Hdf5 file for Alex

### ISSUE THREAD

**Issue by DanielisRutkauskas** [tritemio/FRETBursts#58]
[notebook and data.zip](https://github.com/tritemio/FRETBursts/files/998876/notebook.and.data.zip)

Hi,

I am trying to process some data (data and notebook attached) using ALEX-related functions.  However, I am not able to get past the bpl.plot_alternation_hist(). It all works, however, on the example data file 0023uLRpitc_NTP_20dT_0.5GndCl.hdf5. So the question is: what is so specific to the data file that it is recognized as of ALEX?
Also: why doesn't the data loaded from my file contain attribute d.ph_times_t but instead d.ph_times_m which should only be present after applying loader.alex_apply_period()?

Unrelated issue: after updating to 0.6.3, the combination
filename = OpenFileDialog()
d = loader.photon_hdf5(filename)
does not work. What is the reason?

Thank you,

Danielis

**Comment by tritemio** [comment]
@DanielisRutkauskas, looking at your file it says `measurement_type = 'smFRET'`, (in `/photon_data/measurements_specs`). This means that the measurement is a single-laser smFRET measurement using two detectors.

If your measurement is smFRET-usALEX, i.e. is using two alternated CW lasers and two detectors, then your should use `measurement_type = 'smFRET-usALEX'` (see docs [here](http://photon-hdf5.readthedocs.io/en/0.4/phdata.html#measurement-type)). When using this measurement type you have a new mandatory field that is `alex_period` containing the duration of the alternation period in timestamp units. It is also suggested to add:

- alex_excitation_period1
- alex_excitation_period2
- alex_offset

so that all the parameters of the alternation are fully specified and your don't need to adjust them during the analysis.

For the OpenFileDialog issue, can you please open a new issue posting the error?

**Comment by DanielisRutkauskas** [comment]
Reassembled the HDF5 file according to your recommendations. It worked! Thank you.

**Comment by tritemio** [comment]
Great, thanks for reporting back!
