### ISSUE TITLE
Direct A excitation correction

### ISSUE THREAD

**Issue by DanielisRutkauskas** [tritemio/FRETBursts#60]
Hi,
a question about the definition of the correction factor for direct excitation of acceptor with donor excitation.
Excerpts from the tutorial notebook:
d = loader.photon_hdf5(filename)
d.dir_ex = 0.04

What is the meaning of dir_ex - is it d according to Lee et al. and also dAA according to "Derivation of FRET and S correction formulas", or is it dT according to "Derivation of FRET and S correction formulas" and also dir_ex_t according to "FRET Correction Formulas" in the online manual?

**Comment by tritemio** [comment]
`Data.dir_ex` is the coefficient "dAA" as defined by Lee et al. 2005 and as in eq. (21) in [Applying Corrections in Single-Molecule FRET](https://doi.org/10.1101/083287).

The coefficient `dir_ex_t` corresponding to eq. (24) in the "applying correction ..." paper is used to correct FRET values when calling the function `fretmath.correct_E_gamma_leak_dir()` ([docs](http://fretbursts.readthedocs.io/en/latest/fretmath.html)).

Historically, I first implemented `Data.dir_ex` following Lee et al. 2005 as a property that corrects all the bursts values (so when you plot histograms the correction is applied).
Later I realized that, you can express the A direct excitation in terms of physical parameters, so you can correct also non-ALEX measurements. At the same time I found that all the corrections are better applied after fitting the uncorrected E_PR.
So now my recommended approach is estimating E_PR_mean for a population and then correcting this value with `fretmath.correct_E_gamma_leak_dir()`.

See also this [discussion](https://github.com/tritemio/FRETBursts/issues/55).

**Comment by DanielisRutkauskas** [comment]
Thank you for the reply.
What is your suggestion for finding gamma, in the case of adopting your recommended approach? The question exists because according to Lee et al. leakage and direct excitation correction factors are found from D-only and A-only species in EPRraw/Sraw histogram, respectively. Correcting EPRraw and Sraw with these corrections then yields EPR/S histogram from which gamma is calculated given there exist at least two spiecies with different EPR and medium S. However, with your approach, I understand, this corrected EPR/S histogram is not calculated.

**Comment by tritemio** [comment]
From a set of ALEX measurements you should definitely follow Lee at al. to compute gamma. As a first step you have to estimate leakage and direct excitation (d_aa coefficient). Then the gamma-fitting procedure also gives you beta which is the factor linking d_aa with dir_ex_t. So, with this procedure you can estimate also dir_ex_t that can in principle be used in non-ALEX measurements on the same samples.

When you plot FRET or ALEX histograms you can apply all the corrections and visualize the corrected histogram (or not, it's your choice). My point is, at the end, you probably want to obtain the mean corrected E for one or more populations. What I suggest is simply fitting the RAW E_PR histogram instead of the corrected E histogram. Then, apply the formula to correct this fitted value and obtain E for the population of interest. I suggest this because applying the correction to the entire histogram (i.e. to the burst-level data) can distort the shape of the peaks and render fit less accurate (especially using Gaussian fit).

**Comment by DanielisRutkauskas** [comment]
All right, I see what you mean. Thanks for additional clarifications.

**Comment by tritemio** [comment]
This issue was moved to OpenSMFS/FRETBursts#2
